name: Build and deploy Node.js app to Azure Web App - college-frontend-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and test
        run: |
          npm install
          npm test -- --passWithNoTests

      - name: Zip full project (excluding node_modules and .git)
        run: |
          zip -r app.zip . -x "node_modules/*" ".git/*"

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C67A39AFB9724831A07EE99189D87B79 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0425E16C292B49B8BEEF2F7A30D9911D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3CC8DB7C454F45C0A27A0ACA5AB4EBD4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'college-frontend-webapp'
          slot-name: 'Production'
          package: app.zip
